from abc import ABC, abstractmethod
from typing import Callable, ContextManager


class BaseReporter(ABC):
    @abstractmethod
    def ARRANGE(self, msg: str) -> ContextManager: ...
    @abstractmethod
    def ACT(self, msg: str) -> ContextManager: ...
    @abstractmethod
    def ASSERT(self, msg: str) -> ContextManager: ...

    @abstractmethod
    def step(self, name: str) -> ContextManager: ...
    @abstractmethod
    def attach_text(self, text: str, name: str = ''): ...
    @abstractmethod
    def step_decorator(self, *args, **kwargs) -> Callable: ...
    @abstractmethod
    def static_step_decorator(self, *args, **kwargs) -> Callable: ...

    @abstractmethod
    def set_parent_suite(self, parent_suite_name: str) -> None: ...
    @abstractmethod
    def set_suite(self, suite_name: str) -> None: ...
    @abstractmethod
    def set_sub_suite(self, sub_suite_name: str) -> None: ...
